DROP TABLE IF EXISTS INTEGRATION;

CREATE TABLE INTEGRATION (
       INTEGRATION_ID BIGINT NOT NULL AUTO_INCREMENT,
        COMMENT VARCHAR(255),
        CONFIRMED_FLAG VARCHAR(255),
        DELETE_FLAG VARCHAR(255),
        DESCRIPTION VARCHAR(255),
        INTEGRATED_FLAG VARCHAR(255),
        INTEGRATION_NAME VARCHAR(255) NOT NULL,
        INTEGRATION_TYPE VARCHAR(255) NOT NULL,
        INTERFACE_IN_OUT_TYPE VARCHAR(255),
        RECEIVER VARCHAR(255),
        SENDER VARCHAR(255),
        TOBE_MANAGER VARCHAR(255),
        PRIMARY KEY (INTEGRATION_ID)
    );


INSERT INTO INTEGRATION(COMMENT, CONFIRMED_FLAG, DELETE_FLAG, DESCRIPTION, INTEGRATED_FLAG, INTEGRATION_NAME, INTEGRATION_TYPE, INTERFACE_IN_OUT_TYPE, RECEIVER, SENDER, TOBE_MANAGER)
		VALUES("-", "Y", "N", "DR는 CBP에게 EMAIL 정보를 전송(확인필요)", "N", "EMAIL 전송", "DB_LINK", "INNER", "CBP", "DR", "시스템관리");


INSERT INTO INTEGRATION(COMMENT, CONFIRMED_FLAG, DELETE_FLAG, DESCRIPTION, INTEGRATED_FLAG, INTEGRATION_NAME, INTEGRATION_TYPE, INTERFACE_IN_OUT_TYPE, RECEIVER, SENDER, TOBE_MANAGER)
		VALUES("-", "Y", "N", "DR는 CBP에게 EMAIL 정보를 전송(확인필요)2", "N", "EMAIL 전송", "DB_LINK", "INNER", "CBP", "DR", "시스템관리");


INSERT INTO INTEGRATION(COMMENT, CONFIRMED_FLAG, DELETE_FLAG, DESCRIPTION, INTEGRATED_FLAG, INTEGRATION_NAME, INTEGRATION_TYPE, INTERFACE_IN_OUT_TYPE, RECEIVER, SENDER, TOBE_MANAGER)
		VALUES("-", "Y", "N", "DR는 CBP에게 EMAIL 정보를 전송(확인필요)3", "N", "EMAIL 전송", "DB_LINK", "INNER", "CBP", "DR", "시스템관리");


